name: Validate Helm chart
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'fairscape/**'
jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: helm-check
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./fairscape
        CHART_VALUES: ./fairscape/values.yaml