name: Lint and Test Charts
# Official Helm test workflow
# https://github.com/marketplace/actions/helm-chart-testing
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'fairscape/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        env:
          CT_CHART_DIRS: fairscape
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        env:
          CT_CHART_DIRS: fairscape
        run: ct lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        env:
          CT_CHART_DIRS: fairscape
        run: ct install