name: Validate Helm chart
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'fairscape/**'

jobs:
  helm-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Run helm check action
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./fairscape
        CHART_VALUES: ./fairscape/values.yaml